/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfilRouteImport } from './routes/profil'
import { Route as ProfesseursRouteImport } from './routes/professeurs'
import { Route as ParentsRouteImport } from './routes/parents'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as ConnexionRouteImport } from './routes/connexion'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as AideRouteImport } from './routes/aide'
import { Route as AbsencesRouteImport } from './routes/absences'
import { Route as IndexRouteImport } from './routes/index'

const ProfilRoute = ProfilRouteImport.update({
  id: '/profil',
  path: '/profil',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesseursRoute = ProfesseursRouteImport.update({
  id: '/professeurs',
  path: '/professeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ParentsRoute = ParentsRouteImport.update({
  id: '/parents',
  path: '/parents',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const ConnexionRoute = ConnexionRouteImport.update({
  id: '/connexion',
  path: '/connexion',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const AideRoute = AideRouteImport.update({
  id: '/aide',
  path: '/aide',
  getParentRoute: () => rootRouteImport,
} as any)
const AbsencesRoute = AbsencesRouteImport.update({
  id: '/absences',
  path: '/absences',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aide': typeof AideRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/connexion': typeof ConnexionRoute
  '/eleves': typeof ElevesRoute
  '/parents': typeof ParentsRoute
  '/professeurs': typeof ProfesseursRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aide': typeof AideRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/connexion': typeof ConnexionRoute
  '/eleves': typeof ElevesRoute
  '/parents': typeof ParentsRoute
  '/professeurs': typeof ProfesseursRoute
  '/profil': typeof ProfilRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/absences': typeof AbsencesRoute
  '/aide': typeof AideRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/connexion': typeof ConnexionRoute
  '/eleves': typeof ElevesRoute
  '/parents': typeof ParentsRoute
  '/professeurs': typeof ProfesseursRoute
  '/profil': typeof ProfilRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/absences'
    | '/aide'
    | '/annonces'
    | '/classes'
    | '/connexion'
    | '/eleves'
    | '/parents'
    | '/professeurs'
    | '/profil'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/absences'
    | '/aide'
    | '/annonces'
    | '/classes'
    | '/connexion'
    | '/eleves'
    | '/parents'
    | '/professeurs'
    | '/profil'
  id:
    | '__root__'
    | '/'
    | '/absences'
    | '/aide'
    | '/annonces'
    | '/classes'
    | '/connexion'
    | '/eleves'
    | '/parents'
    | '/professeurs'
    | '/profil'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AbsencesRoute: typeof AbsencesRoute
  AideRoute: typeof AideRoute
  AnnoncesRoute: typeof AnnoncesRoute
  ClassesRoute: typeof ClassesRoute
  ConnexionRoute: typeof ConnexionRoute
  ElevesRoute: typeof ElevesRoute
  ParentsRoute: typeof ParentsRoute
  ProfesseursRoute: typeof ProfesseursRoute
  ProfilRoute: typeof ProfilRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/profil': {
      id: '/profil'
      path: '/profil'
      fullPath: '/profil'
      preLoaderRoute: typeof ProfilRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professeurs': {
      id: '/professeurs'
      path: '/professeurs'
      fullPath: '/professeurs'
      preLoaderRoute: typeof ProfesseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/parents': {
      id: '/parents'
      path: '/parents'
      fullPath: '/parents'
      preLoaderRoute: typeof ParentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/connexion': {
      id: '/connexion'
      path: '/connexion'
      fullPath: '/connexion'
      preLoaderRoute: typeof ConnexionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/aide': {
      id: '/aide'
      path: '/aide'
      fullPath: '/aide'
      preLoaderRoute: typeof AideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/absences': {
      id: '/absences'
      path: '/absences'
      fullPath: '/absences'
      preLoaderRoute: typeof AbsencesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AbsencesRoute: AbsencesRoute,
  AideRoute: AideRoute,
  AnnoncesRoute: AnnoncesRoute,
  ClassesRoute: ClassesRoute,
  ConnexionRoute: ConnexionRoute,
  ElevesRoute: ElevesRoute,
  ParentsRoute: ParentsRoute,
  ProfesseursRoute: ProfesseursRoute,
  ProfilRoute: ProfilRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
