/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProfesseursRouteImport } from './routes/professeurs'
import { Route as ElevesRouteImport } from './routes/eleves'
import { Route as ClassesRouteImport } from './routes/classes'
import { Route as AnnoncesRouteImport } from './routes/annonces'
import { Route as IndexRouteImport } from './routes/index'

const ProfesseursRoute = ProfesseursRouteImport.update({
  id: '/professeurs',
  path: '/professeurs',
  getParentRoute: () => rootRouteImport,
} as any)
const ElevesRoute = ElevesRouteImport.update({
  id: '/eleves',
  path: '/eleves',
  getParentRoute: () => rootRouteImport,
} as any)
const ClassesRoute = ClassesRouteImport.update({
  id: '/classes',
  path: '/classes',
  getParentRoute: () => rootRouteImport,
} as any)
const AnnoncesRoute = AnnoncesRouteImport.update({
  id: '/annonces',
  path: '/annonces',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/professeurs': typeof ProfesseursRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/professeurs': typeof ProfesseursRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/annonces': typeof AnnoncesRoute
  '/classes': typeof ClassesRoute
  '/eleves': typeof ElevesRoute
  '/professeurs': typeof ProfesseursRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/annonces' | '/classes' | '/eleves' | '/professeurs'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/annonces' | '/classes' | '/eleves' | '/professeurs'
  id: '__root__' | '/' | '/annonces' | '/classes' | '/eleves' | '/professeurs'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnnoncesRoute: typeof AnnoncesRoute
  ClassesRoute: typeof ClassesRoute
  ElevesRoute: typeof ElevesRoute
  ProfesseursRoute: typeof ProfesseursRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/professeurs': {
      id: '/professeurs'
      path: '/professeurs'
      fullPath: '/professeurs'
      preLoaderRoute: typeof ProfesseursRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/eleves': {
      id: '/eleves'
      path: '/eleves'
      fullPath: '/eleves'
      preLoaderRoute: typeof ElevesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/classes': {
      id: '/classes'
      path: '/classes'
      fullPath: '/classes'
      preLoaderRoute: typeof ClassesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/annonces': {
      id: '/annonces'
      path: '/annonces'
      fullPath: '/annonces'
      preLoaderRoute: typeof AnnoncesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnnoncesRoute: AnnoncesRoute,
  ClassesRoute: ClassesRoute,
  ElevesRoute: ElevesRoute,
  ProfesseursRoute: ProfesseursRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
